VPATH=include src src/mbsapi

# gdc -Iinclude -Isrc -c -o gate.d src/gate.d -MMD `pkg-config gtk4 --cflags` -MF gate.d.dep


CFLAGS = `pkg-config elderpt-0.1 alsa gtk4 gsl --cflags` -s -O4
LDFLAGS = `pkg-config elderpt-0.1 alsa gtk4 gsl --libs` -s -O4 -Wl,-rpath=/home/michael/.local/lib -lX11



all: fairy

# translate .d source files into .di interface files
include/%.di: src/%.d
	dmd -o- -Iinclude -Isrc -i -H $< -Hd=include || true # for one file dmd gives an error and the " || true " prevents make from quitting in that case

# gtk4_import also has function bodies, so there needs to be an object file created for it (instead of just a .i file)
gtk4_import.o: src/gtk4_import.c
	gdc -Iinclude -Isrc $(CFLAGS) -fversion=gtk4_native -c $<

OBJECTS=\
	alsa.o                 \
	app.o                  \
	asciirender.o          \
	audiodaq.o             \
	cmdline.o              \
	color.o                \
	expression.o           \
	fairy.o                \
	functions.o            \
	gate.o                 \
	graphics.o             \
	interactive.o          \
	interactive_demo.o     \
	graphics_gtk4_native.o \
	gtk4_import.o          \
	mbsapi_import.o        \
	elderpt.o              \
	histogram.o            \
	item.o                 \
	multifit_nlin.o        \
	serializeJSON.o        \
	transform.o            \
	ui.o                   \
	value.o                \
	waveform.o             \
	f_evcli.o              \
	f_evt.o                \
	f_his_swpbas.o         \
	f_his_toupper.o        \
	fLmd.o                 \
	f_mbs_status.o         \
	f_radware.o            \
	f_stccomm.o            \
	f_swaplw.o             \
	f_ut_compress.o        \
	f_ut_seg_show.o        \
	f_ut_status.o          \
	f_ut_time.o            \
	f_ut_utime.o           	

include fairy.d.dep

%.o: %.c
	gcc -Isrc/mbsapi $(CFLAGS) -c $<

%.o: %.d
	gdc -Iinclude $(CFLAGS) -fversion=gtk4_native -fversion=elderpt -fversion=alsa -c $<

fairy: $(PREPROCESSED) $(OBJECTS)
	gdc -Iinclude $(CFLAGS) -fversion=gtk4_native -fversion=elderpt -fversion=alsa -o $@ $+ $(LDFLAGS) 

clean:
	rm -f include/*.di include/*.i *.o fairy 
