VPATH=src
CFLAGS = `pkg-config alsa gtk4 gsl --cflags`
LDFLAGS = `pkg-config alsa gtk4 gsl --libs`

%.i: %.c
	gcc $(CFLAGS) -E $< > $@

# 	src/elderpt.d              \

OBJECTS=\
	alsa.o                 \
	app.o                  \
	asciirender.o          \
	audiodaq.o             \
	cmdline.o              \
	expression.o           \
	fairy.o                \
	functions.o            \
	graphics.o             \
	graphics_gtk4_native.o \
	gtk4_import.o          \
	histogram.o            \
	item.o                 \
	multifit_nlin.o        \
	serializeJSON.o        \
	transform.o            \
	ui.o                   \
	value.o                \
	waveform.o             

%.o: %.d
	make -C include
	gdc -Isrc $(CFLAGS) -fversion=gtk4_native -c $<

fairy: $(OBJECTS)
	gdc -Iinclude $(CFLAGS) -fversion=gtk4_native -o $@ $+ $(LDFLAGS) 

includes: 
	make -C include

clean:
	rm -f src/*.i *.i *.o newco 
